name: ExChange
main: HiroTeam\exchange\ExChange
version: 1.0.0
api: 3.0.0
author: HiroTeam
depend: [EconomyAPI]
description: ExChange/Bourse Plugin
commands:
  exchange:
    description: use exchange command
    usage: /exchange
